### ISSUE TITLE
Question about duplication

### ISSUE THREAD

**Issue by gep13** [sushihangover/Cake.AppleSimulator#9]
I just noticed this addin, and I wanted to ask a question...

Is there duplication of effort/functionality between this package and the original package from @ghuntley?

Any reason to not simply work on the same package together?  I am just worried about dilution of the project, and people being unclear about which package to use.

Thanks!

**Comment by sushihangover** [comment]
As I made these changes ghauntly accepted the first three PRs and after a further review accepted the fourth. 

>FYI : I fork'd and published as Cake.AppleSimulator.SushiHangover as I needed these additional features for actual production usage ASAP

The full PR/conversation thread: https://github.com/ghuntley/Cake.AppleSimulator/pull/4

He has now granted me maintainer access on his repo.

The published nuget on his repo does not currently reflect any of these changes. An issue really needs to be created on that repo so we can track/publish the new changes under his Nuget and delist mine to allow project to continue to pull it till they change to the update "official" version.

**Comment by gep13** [comment]
@sushihangover this sounds perfect, thank you for taking the time to respond.

Yes, I think once @ghuntley and yourself publish a new version of the original nuget package, de-listing your version makes a lot of sense.
